# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'a.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x07\x61.proto\"V\n\x0eUserSubmittion\x12\x10\n\x08Question\x18\x01 \x01(\t\x12\x0e\n\x06\x41nswer\x18\x02 \x01(\t\x12\x0e\n\x06UserId\x18\x03 \x01(\t\x12\x12\n\nResponceId\x18\x04 \x01(\t\"\xa5\x01\n\x16UserSubmittionResponse\x12\x10\n\x08Question\x18\x01 \x01(\t\x12\x0e\n\x06\x41nswer\x18\x02 \x01(\t\x12\x0e\n\x06UserId\x18\x03 \x01(\t\x12\x0f\n\x07\x43larity\x18\x04 \x01(\t\x12\x0c\n\x04Tone\x18\x05 \x01(\t\x12\x11\n\tRelevance\x18\x06 \x01(\t\x12\x14\n\x0cOverallScore\x18\x07 \x01(\t\x12\x11\n\tSuggestio\x18\x08 \x01(\t2Y\n\x15UserSubmittionService\x12@\n\x14SubmitUserSubmittion\x12\x0f.UserSubmittion\x1a\x17.UserSubmittionResponseB,Z*smart-interview-platform/grpcclient/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*smart-interview-platform/grpcclient/common'
  _globals['_USERSUBMITTION']._serialized_start=11
  _globals['_USERSUBMITTION']._serialized_end=97
  _globals['_USERSUBMITTIONRESPONSE']._serialized_start=100
  _globals['_USERSUBMITTIONRESPONSE']._serialized_end=265
  _globals['_USERSUBMITTIONSERVICE']._serialized_start=267
  _globals['_USERSUBMITTIONSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
