// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: a.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserSubmittionService_SubmitUserSubmittion_FullMethodName = "/UserSubmittionService/SubmitUserSubmittion"
)

// UserSubmittionServiceClient is the client API for UserSubmittionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSubmittionServiceClient interface {
	SubmitUserSubmittion(ctx context.Context, in *UserSubmittion, opts ...grpc.CallOption) (*UserSubmittionResponse, error)
}

type userSubmittionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSubmittionServiceClient(cc grpc.ClientConnInterface) UserSubmittionServiceClient {
	return &userSubmittionServiceClient{cc}
}

func (c *userSubmittionServiceClient) SubmitUserSubmittion(ctx context.Context, in *UserSubmittion, opts ...grpc.CallOption) (*UserSubmittionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSubmittionResponse)
	err := c.cc.Invoke(ctx, UserSubmittionService_SubmitUserSubmittion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSubmittionServiceServer is the server API for UserSubmittionService service.
// All implementations must embed UnimplementedUserSubmittionServiceServer
// for forward compatibility.
type UserSubmittionServiceServer interface {
	SubmitUserSubmittion(context.Context, *UserSubmittion) (*UserSubmittionResponse, error)
	mustEmbedUnimplementedUserSubmittionServiceServer()
}

// UnimplementedUserSubmittionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserSubmittionServiceServer struct{}

func (UnimplementedUserSubmittionServiceServer) SubmitUserSubmittion(context.Context, *UserSubmittion) (*UserSubmittionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitUserSubmittion not implemented")
}
func (UnimplementedUserSubmittionServiceServer) mustEmbedUnimplementedUserSubmittionServiceServer() {}
func (UnimplementedUserSubmittionServiceServer) testEmbeddedByValue()                               {}

// UnsafeUserSubmittionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSubmittionServiceServer will
// result in compilation errors.
type UnsafeUserSubmittionServiceServer interface {
	mustEmbedUnimplementedUserSubmittionServiceServer()
}

func RegisterUserSubmittionServiceServer(s grpc.ServiceRegistrar, srv UserSubmittionServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserSubmittionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserSubmittionService_ServiceDesc, srv)
}

func _UserSubmittionService_SubmitUserSubmittion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSubmittion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSubmittionServiceServer).SubmitUserSubmittion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSubmittionService_SubmitUserSubmittion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSubmittionServiceServer).SubmitUserSubmittion(ctx, req.(*UserSubmittion))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSubmittionService_ServiceDesc is the grpc.ServiceDesc for UserSubmittionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSubmittionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserSubmittionService",
	HandlerType: (*UserSubmittionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitUserSubmittion",
			Handler:    _UserSubmittionService_SubmitUserSubmittion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a.proto",
}
